### ISSUE TITLE
slow MBVectorTileDecoder loading

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#226]
With the 4.1.3 on android, MBVectorTileDecoder is very slow loading
i load it using this:
```java
public ZippedAssetPackage getStyleZippedAsset() {
        if (styleAsset == null) {
            BinaryData data = AssetUtils.loadAsset(vectorStyleFile);
            styleAsset = new ZippedAssetPackage(data);
        }
        return styleAsset;
    }
    
    public TileLayer getLayer() {
        return layer;
    }

    public VectorTileDecoder getVectorTileDecoder() {
        if (vectorTileDecoder == null) {
            vectorTileDecoder = new MBVectorTileDecoder(new CompiledStyleSet(getStyleZippedAsset(), style));
        }
        return vectorTileDecoder;
    }
```
It takes around 1 min if not more.
Here is my zip style derived from the official one
[carto.zip](https://github.com/CartoDB/mobile-sdk/files/2098077/carto.zip)

**Comment by farfromrefug** [comment]
After some investigation it does come from the style. Is there any way to debug what might be so long to load in this style?

**Comment by mtehver** [comment]
I made some measurements, and the loading time seems to be about 2-3 seconds on my Android device (Pixel 2). So it is quite slow, but quite far from reported 1 min. I made some optimizations to the CartoCSS compiler module that makes both style and tile loading a bit faster (style loading about 25% for the modified style).

**Comment by farfromrefug** [comment]
@mtehver great improvement! Did you try with the attached style? Cause the issue only happens with this one.

**Comment by mtehver** [comment]
Yes, I used Voyager style from the attached style asset. Should I try some other style?

**Comment by farfromrefug** [comment]
@mtehver no i only use voyager.  Could you make a test android sdk so that i can test on my side? I could report the logcat if you improve the css report errors from https://github.com/CartoDB/mobile-sdk/issues/229

Thanks

**Comment by mtehver** [comment]
@farfromrefug Hi. I have uploaded the latest dev build: [https://drive.google.com/open?id=10wnOciDanRWxmJa3QKDK6QWpH0SnXURy](https://drive.google.com/open?id=10wnOciDanRWxmJa3QKDK6QWpH0SnXURy)

This build includes CSS compiler optimisations, minor error reporting fixes and also TileUtils class as part of the API. All feedback is welcome.

**Comment by farfromrefug** [comment]
@mtehver great! I saw your commits and was waiting for a build to test :D
And thank you for the TileUtils, that's a great addition.

Will test that  and report

**Comment by farfromrefug** [comment]
@mtehver finally working on Carto again!
I now use Carto natively (android) and within Nativescript.
I still have some styles which are really slow loading but i dont know why

carto_test takes 10 sec now (but works perfectly) while bright takes less than a second.
I am talking about the time from addLayer to full rendering (for cached tiles).
[bright.zip](https://github.com/CartoDB/mobile-sdk/files/2535472/bright.zip)
[carto_test.zip](https://github.com/CartoDB/mobile-sdk/files/2535473/carto_test.zip)

**Comment by farfromrefug** [comment]
@mtehver still seeing that issue. The loading factor is quite crazy. Might have some insight?
Would really like to fix this.

Thanks

**Comment by farfromrefug** [comment]
i think it is related to assets being loaded multiple times. Needs for testing though

**Comment by farfromrefug** [comment]
@mtehver it is not related to assets being loaded multiple times. I think it is related to the way rules are written.
If i write this:
```less
#contour {
  [zoom>=12][ele>300],
  [zoom>=14][ele>200],
  [zoom>=16][ele>0] {
    line-cap: butt;
    line-width: 0.68;
    line-color: #387127;
    line-opacity: 0.3;
    [index=5][zoom>=14],
    [index=10] {
      line-opacity: 0.5; 
      line-width: 0.96; 
    }
  }
}
```

it is much faster than writting this:
```less
#contour
  [zoom>=12][ele>300],
  [zoom>=14][ele>200],
  [zoom>=16][ele>0] {
    line-cap: butt;
    line-width: 0.68;
    line-color: #387127;
    line-opacity: 0.3;
  [index=5][zoom>=14],
  [index=10] {
    line-opacity: 0.5; 
    line-width: 0.96; 
  }
}
```
I dont have number but i can really see the difference. Does it make sense? Do you see why this would happen?
