### ISSUE TITLE
[mss] use icon fonts

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#288]
Just had a crazy idea for POI icons. Instead of using png/svg we could use icon font (like icomoon).

I know it can work with something like this:
```less
{
    ::icon {
      text-name: '';
      text-face-name: @maki;
      text-fill: @peak_label;
    }
    ::label {
      text-name: @name ?  (@name + '\n'  + [ele] + 'm'): '';
      text-face-name: @mont;
      text-size: linear([view::zoom], (8, 9.0), (14, 12)) + [ele] * 0.00001;
      text-fill: @peak_label;
      text-halo-fill: @peak_halo;
      text-halo-radius: 1;
      text-halo-rasterizer: fast;
      text-allow-overlap: false;
      text-wrap-width: 80;
      text-line-spacing:	-1;
      text-dy: 10;
      text-min-distance: 300;
    }
  }
```

There are 2 issues though. How can input unicode char for the ```text-name```
I tried ```'\ue962'```,```'\e962'``` and `````` but nothing seems to work (though putting simple ```'test'``` works). Any idea on how to input it?

Also the last thing would be a map function from pio class/subclass to unicode char. My question is then can we write functions in ```mss```? Or could i read it from a json or something? I don't really know what the carto mobile mss engine is capable of.
I looked at [turbocarto](https://carto.com/developers/styling/turbocarto/) but i dont think it is working in the mobile sdk.

Thanks
