### ISSUE TITLE
icons not appearing 

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#289]
I now use that style trick:
```less
//Peak labels
#mountain_peak [zoom>=4][comment =~'.*Highest.*'],
#mountain_peak[zoom>=4][comment =~'.*highest.*'],
#mountain_peak[zoom>=7][ele>=4000],
#mountain_peak[zoom>=8][ele>=3000],
#mountain_peak[zoom>=9][ele>=2000],
#mountain_peak[zoom>=10][ele>=1500],
#mountain_peak[zoom>=11] {
    ::icon {
      text-placement: [nuti::markers3d];
      text-name: [nuti::maki-mountain];
      text-size: 14 + [ele] * 0.00001;
      text-face-name: @maki;
      text-fill: @peak_label;
    }
    ::label [zoom>=11] {
      text-name: @name ?  (@name + '\n'  + [ele] + 'm'): '';
      text-face-name: @mont;
      text-size: linear([view::zoom], (8, 9.0), (14, 12)) + [ele] * 0.00001;
      text-fill: @peak_label;
      text-halo-fill: @peak_halo;
      text-halo-radius: 1;
      text-halo-rasterizer: fast;
      text-allow-overlap: false;
      text-wrap-width: step([zoom], (15, 80), (16, 90), (18, 100));
      text-line-spacing:	-1;
      text-dy: 10;
      text-min-distance: 300;
    }
}
```
to show markers using font icons. Working great except that sometimes they are not draw without any particular reason.
The order of ```::icon``` and ```::label``` means that the icon has more priority over the label.
It works well when zooming out, but not when zooming in / appearing.

In this video you can see that the ```Mont Jalla``` icon is not appearing when zooming in. Only the text. Though when zooming out it behaves correctly.
It seems like a bug to me. May be it has something to do with the fact that nor the icon or the label are drawn on zoom <= 11.

![sdk_gphone_x86PSR1 180720 061mguillon05222019145850](https://user-images.githubusercontent.com/655344/58176582-ddd85800-7ca2-11e9-90a9-6ab7644438aa.gif)
