### ISSUE TITLE
features are not always returned by VectorTileEventListener

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#290]
Using this for the icons show
```less
#mountain_peak [zoom>=4][comment =~'.*Highest.*'],
#mountain_peak[zoom>=4][comment =~'.*highest.*'],
#mountain_peak[zoom>=7][ele>=4000],
#mountain_peak[zoom>=8][ele>=3000],
#mountain_peak[zoom>=9][ele>=2000],
#mountain_peak[zoom>=10][ele>=1500],
#mountain_peak[zoom>=11] {
    ::icon {
      text-placement: [nuti::markers3d];
      text-name: [nuti::maki-mountain];
      text-size: 14 + [ele] * 0.00001;
      text-face-name: @maki;
      text-fill: @peak_label;
    }
}
```

You can see in the video that features not always clickable. Behind what is happening is that the peaks (features) are not returned by ```VectorTileEventListener``` (i only return true if it a peak)
. Seems like they are not there.
However if i click on another one (plus map move to focus), the element gets "clickable" (returned by ```VectorTileEventListener```)
![sdk_gphone_x86PSR1 180720 061mguillon05222019150816](https://user-images.githubusercontent.com/655344/58177022-d6657e80-7ca3-11e9-8c04-6da21c2b2057.gif)
