### ISSUE TITLE
[CartoCSS]issue with nuti variable in zoom prop

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#306]
I am trying to make sure my selected tile element is always visible.

so i try something like this 
```less
[osm_id = 'nuti::selected_id'],
[name = 'nuti::selected_name'] {
text-fil: ...
}
```
That rule does not seem to work here.
However i know that ```nuti::selected_name``` and ```nuti::selected_id``` are correct and that the comparaison actually work. If i do this:
```less
@id_test: ([osm_id] = [nuti::selected_id]) ? #f00 : #fff;
@name_test: ([name] = [nuti::selected_name]) ? #0f0 : #fff;
```
And if i use those colors, i do see the color change when i change the nuti properties.

It seems like it does not work in zoom "rules".
What is strange is that this work ```['nuti::buildings'=1]```

any idea?
