### ISSUE TITLE
wrong label priority

### ISSUE THREAD

**Issue by farfromrefug** [CartoDB/mobile-sdk#309]
I have something like this for transportation_name
```less
[class=motorway][zoom>=9],
	[class=trunk][zoom>=10],
	[class=primary][zoom>=14],
	[class=track][zoom>=15],
	[class=tertiary][zoom>=15],
	[class=secondary][zoom>=15],
	[class=minor][zoom>=16],
	[class=service][zoom>=17],
	[class=path][zoom>=17]{
		text-avoid-edges: false;
		text-name: @name;
		text-placement: line;
		// text-wrap-before: true;
		text-face-name: @mont;
		text-fill: @road_text;
		text-halo-fill: @minor_halo;
		text-halo-radius: 1;
		text-halo-rasterizer: fast;
		text-min-distance: 5;
		text-size: linear([view::zoom], (13, 6.0), (18, 8.0));
		text-vertical-alignment: middle;
		
		[class=motorway],
		[class=trunk],
		[class=primary]{
			text-halo-fill: @primary_halo;
			text-size: linear([view::zoom], (13, 6.0), (18, 13.0)) + 0.00004;
			[class=motorway], [class=trunk] { text-halo-fill: @motorway_halo; }
		}
		
		[class=secondary],
		[class=tertiary]{
			text-size: linear([view::zoom], (13, 6.0), (18, 12.0)) + 0.00003;
		}
		[class=minor]{
			text-size: linear([view::zoom], (13, 6.0), (18, 10.0)) + 0.00002;
		}
		[class=service]{
			text-size: linear([view::zoom], (13, 6.0), (18, 10.0)) + 0.00001;
		}
	}
```
As you can see i use +0.00000x to try and give priority to higher class labels
However it does not work and i am wondering if it is related to ```text-min-distance```

In the next screenshot look at the circles. I see the footway label when i should see the minor street label.
![Screenshot_1565691347](https://user-images.githubusercontent.com/655344/62934178-3f045900-bdc4-11e9-9866-dd1444f58db8.png)

Any idea?
